### ISSUE TITLE
Hello from BrainGlobe :wave: 

### ISSUE THREAD

**Issue by adamltyson** [spkware/vvasp#1]
Hi,

This isn't really an issue, but I saw that your tool uses @BrainGlobe. I wanted to reach out to say please get in touch if there's anything we can do to help you maintain your software, and minimise the impact of any changes on the BrainGlobe side. Feel free to join the [BrainGlobe Zulip chat](https://brainglobe.zulipchat.com/) to keep up to date and ask us any questions. 

Also, if you don't mind, we'd love to add your tool to [our list of community built tools](https://brainglobe.info/community/external-tools.html).

**Comment by mdmelin** [comment]
Hey @adamltyson thanks for reaching out and for your work on Brainglobe! Happy to have the repo added to your list of tools.
